version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "ruby main.rb -o 0.0.0.0"
    ports:
      - "4567:4567"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - ENV=development
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - "./init_db/:/docker-entrypoint-initdb.d/"
      - "./docker/data/:/var/lib/mysql/"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
